Repository adrienjoly/npm-pdfreader, pull requests merged in 2020-09, with the labels that each got.

#62 fix: Ease contributions
  .eslintrc.json
  package.json
  parseAsBuffer.js
Labels: bug, enhancement

#61 add ability to open pdfs with password
  PdfReader.js
  README.md
  test/sample-with-password.pdf
  test/test-snapshot.log
  test/test.js
Labels: enhancement

#63 fix(deps): Update dependencies
  .circleci/config.yml
  PdfReader.js
  README.md
  Rule.js
  lib/ColumnsParser.js
  lib/LOG.js
  lib/SequentialParser.js
  lib/TableParser.js
  lib/parseColumns.js
  lib/parseTable.js
  package-lock.json
  package.json
  parse.js
  parseAsBuffer.js
  test/test.js
Labels: dependencies

#64 fix(npm): Fix automatic releases to npm
  package.json
Labels: bug

#67 fix(ci): Switch to GitHub Actions => reconfigure semantic-release
  .circleci/config.yml
  .github/workflows/nodejs.yml
  package.json
Labels: bug, enhancement

#65 fix(npm): Reduce package size by excluding tests
  .npmignore
Labels: enhancement

#66 fix(tests): Remove large PDF file (old regression test)
  package.json
  test/issue-14-uncaught-error.pdf
Labels: enhancement

#68 fix: CI badge in README.md
  README.md
Labels: enhancement
